repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: debug-statements
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-merge-conflict
    - id: check-symlinks
    - id: detect-private-key
    - id: name-tests-test
    - id: requirements-txt-fixer
  - repo: https://github.com/pycqa/isort
    rev: 5.6.3
    hooks:
      - id: isort
        args: ['--profile', 'black', '--filter-files']
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
  - repo: git@github.com:humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable', '--expand-star-imports']
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: 'v2.6.0'
    hooks:
      - id: pylint
        args: ['--disable=all', '--enable="bad-whitespace,bad-indentation,line-too-long"']
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
    -   id: forbid-crlf
    -   id: remove-crlf
    -   id: forbid-tabs
    -   id: remove-tabs
    -   id: insert-license
        files: \.py$
        args:
        - --license-filepath
        - docs/LICENSE-header.txt          # defaults to: LICENSE.txt
        - --comment-style
        - "#"
